stages:
  - deploy

deploy_vercel:
  stage: deploy
  image: node:18
  script:
    - npm install -g vercel
    - vercel --prod --yes --token=$VERCEL_TOKEN  # Deploy to Vercel without confirmation
  only:
    - dev  # Change this to your deployment branch

