stages:
  - deploy

deploy_vercel:
  stage: deploy
  image: node:18
  script:
    - cd fe_invotrax
    - npm install -g vercel
    c:\Users\Mahdy\Documents\Kuliah\Akademik\Semester 6\Propensi\Project\BE\.gitlab-ci.yml
  only:
    - dev  # Change this to your deployment branch


